# Generated by Django 4.0 on 2022-08-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_objetdeal_code_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetdeal',
            name='code',
            field=models.CharField(default=10, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetdeal',
            name='notif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetdeal',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetdeal',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En cours', max_length=10),
        ),
        migrations.DeleteModel(
            name='DemandeDeal',
        ),
    ]
