# Generated by Django 4.0 on 2022-08-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Telephone'),
        ),
    ]
